_target_: src.recipe.geolocation.model_module.PowsmGeolocationModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.LinearLR
  _partial_: true
  total_iters: 100
  last_epoch: -1

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 5

hf_cache_dir: ${paths.exp_dir}/powsm_cache
hf_repo: espnet/powsm
# provide paths to override from local files instead of HF repo
s2t_train_config: null
s2t_model_file: null
bpemodel: null
stats_file: null