_target_: src.recipe.language_id.model_module.LanguageIdModel

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.LinearLR
  _partial_: true
  total_iters: 100
  last_epoch: -1

model:
  _target_: src.model.wav2vec2phoneme.builders.build_wav2vec2phoneme_model
  hf_repo: facebook/wav2vec2-lv-60-espeak-cv-ft
# facebook/wav2vec2-lv-60-espeak-cv-ft
# facebook/wav2vec2-xlsr-53-espeak-cv-ft
# ctaguchi/wav2vec2-large-xlsr-japlmthufielta-ipa1000-ns

num_classes: 102  # FLEURS has 102 languages. This will be automatically set from datamodule if available.
freeze_encoder: true

