# @package _global_

defaults:
  - _self_
  - data: vaani_geolocation # choose datamodule with `test_dataloader()` for evaluation
  - model: powsm_geolocation
  - logger: csv
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

train: False
test: True
tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
